### ISSUE TITLE
Clarification needed in Cosmos generator documentation

### ISSUE THREAD

**Issue by matzipan** [nasa/fprime#112]
```
$ ./run_cosmosgen.sh 
BUILD_ROOT is: /home/andrei/Workspace/fprime
make: *** No rule to make target 'print_python_base'.  Stop.
PYTHON_BASE: 
PYTHONPATH: /home/andrei/Workspace/fprime/Autocoders/Python/src
Traceback (most recent call last):
  File "/home/andrei/Workspace/fprime/Autocoders/Python/bin/cosmosgen.py", line 23, in <module>
    from fprime_ac.utils.cosmos import CosmosGenerator
  File "/home/andrei/Workspace/fprime/Autocoders/Python/src/fprime_ac/utils/cosmos/CosmosGenerator.py", line 21, in <module>
    from fprime_ac.utils.cosmos.writers import ChannelWriter
  File "/home/andrei/Workspace/fprime/Autocoders/Python/src/fprime_ac/utils/cosmos/writers/ChannelWriter.py", line 23, in <module>
    from fprime_ac.utils.cosmos.templates import Channel
ImportError: cannot import name Channel
Build vars set, running cosmosgen.py
```

Only `Channel.tmpl` exists: 
```
$ ls -al /home/andrei/Workspace/fprime/Autocoders/Python/src/fprime_ac/utils/cosmos/templates/Channel.tmpl 
-rw-r--r-- 1 andrei andrei 904 Dez  2 14:11 /home/andrei/Workspace/fprime/Autocoders/Python/src/fprime_ac/utils/cosmos/templates/Channel.tmpl
```

**Comment by matzipan** [comment]
This one is a false alarm. I did not run the compile_template step. Perhaps [this](https://github.com/nasa/fprime/blob/master/Autocoders/Python/src/fprime_ac/utils/cosmos/README.md#3-running-the-tool) section should be rewritten to clarify this. Besides, the path to `compile_templates.sh` is out date.
