### ISSUE TITLE
Time::getContext() limited to returning U8

### ISSUE THREAD

**Issue by abcouwer-jpl** [nasa/fprime#1230]
| | |
|:---|:---|
|**_F´ Version_**| devel |
|**_Affected Component_**| Fw::Time  |
---
## Problem Description

The Time class declares getContext() as returning FwTimeContextStoreType in the [hpp](https://github.com/nasa/fprime/blob/8db8e4f22255eb5c9359043dab70f9442a63f82c/Fw/Time/Time.hpp#L33) , but defines getContext() as returning U8 in the [cpp](https://github.com/nasa/fprime/blob/8db8e4f22255eb5c9359043dab70f9442a63f82c/Fw/Time/Time.cpp#L146) .

This limits the definition of FwTimeContextStoreType to U8. We'd like to use the Context to store a boot count, but 0-254 is a bit constraining in terms of number of boots. 

## How to Reproduce

1. Define FwTimeContextStoreType as something other than U8
2. Build a Topology

I got

```
/home/abcouwer/Dev/fprime-fwca/Fw/Time/Time.cpp:146:8: error: no declaration matches ‘U8 Fw::Time::getContext() const’
  146 |     U8 Time::getContext(void) const {
      |        ^~~~
In file included from /home/abcouwer/Dev/fprime-fwca/Fw/Time/Time.cpp:1:
/home/abcouwer/Dev/fprime-fwca/Fw/Time/Time.hpp:33:36: note: candidate is: ‘U16 Fw::Time::getContext() const’
   33 |             FwTimeContextStoreType getContext(void) const; // !< get the context value
      |                                    ^~~~~~~~~~
In file included from /home/abcouwer/Dev/fprime-fwca/Fw/Time/Time.cpp:1:
/home/abcouwer/Dev/fprime-fwca/Fw/Time/Time.hpp:10:11: note: ‘class Fw::Time’ defined here
   10 |     class Time: public Serializable {
      |           ^~~~
```

## Expected Behavior

Would be nice to have flexibility here. If it has never been tweaked before, I forsee issues with GDS or other parts of the framework. I haven't tried changing the Fw yet and seeing how that goes in Topology and GDS. I can update this issue and PR if I make one.

**Comment by abcouwer-jpl** [comment]
[fprime-tools explicitly defines time context as a U8](https://github.com/fprime-community/fprime-tools/blob/f12fcb17df4add2c343959dc5ebb1b144bedcef6/src/fprime/common/models/serialize/time_type.py#L80), so modifying time context type in a deployment (I tried U16) will cause default fprime-gds to fail to decode time types. In my testing, decoding an event failed, subsequent parts of the packet caused more issues.

```
INFO] Running Application: /usr/bin/python3
 * Serving Flask app "fprime_gds.flask.app"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO] F prime is now running. CTRL-C to shutdown all components.
Event decode exception Value 788529152 out of range!
Traceback (most recent call last):
  File "/home/abcouwer/.local/lib/python3.8/site-packages/fprime_gds/common/decoders/event_decoder.py", line 120, in decode_args
    arg_obj.deserialize(arg_data, offset)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/fprime/common/models/serialize/enum_type.py", line 100, in deserialize
    raise TypeRangeException(int_val)
fprime.common.models.serialize.type_exceptions.TypeRangeException: Value 788529152 out of range!
[2022-03-08 09:27:48,619] ERROR in app: Exception on /events [GET]
Traceback (most recent call last):
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/fprime_gds/flask/events.py", line 66, in get
    format_string_template(event.template.format_str, tuple([arg.val for arg in event.args])),
TypeError: 'NoneType' object is not iterable
[2022-03-08 09:27:48,974] ERROR in app: Exception on /events [GET]
Traceback (most recent call last):
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/abcouwer/.local/lib/python3.8/site-packages/fprime_gds/flask/events.py", line 66, in get
    format_string_template(event.template.format_str, tuple([arg.val for arg in event.args])),

```
