### ISSUE TITLE
Serialized I8 becomes U8

### ISSUE THREAD

**Issue by sommercharles** [nasa/fprime#197]
### Bug description:

I8 members of a serializable seem to lose signedness and become U8, thus throwing `fprime.common.models.serialize.type_exceptions.TypeRangeException` from i8_type.py when using a negative I8 value.

### Steps to reproduce bug:
Clone and install F' master branch per installation instructions.
Follow Math tutorial up to the end.

Change val1, factor1 and factor2 type in all serializables, parameters and channels by I8 (to also avoid issue #173).
Change val2 type by I16.
Change result type by I32.
Adjust cpp and hpp files following the change.

Purge, generate, install the Ref project and launch GDS.

Send mathReceiver.MR_SET_FACTOR1 with 1
Send mathSender.MS_DO_MATH with 1, 1, ADD
Verify channel mathSender.MS_RES = 2

To trigger the bug:
Send mathSender.MS_DO_MATH with -1, 2, SUBTRACT

Here are the error messages:

```
Event decode exception Value 255 out of range!
Traceback (most recent call last):
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/decoders/event_decoder.py", line 113, in decode_args
    arg_obj.deserialize(arg_data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 55, in deserialize
    self._deserialize('B', data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/type_base.py", line 58, in _deserialize
    self.val = struct.unpack_from(tformat, data, offset)[0]
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 42, in val
    self._check_val(val)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 34, in _check_val
    raise TypeRangeException(val)
fprime.common.models.serialize.type_exceptions.TypeRangeException: 255
[2020-07-21 23:01:58,227] ERROR in app: Exception on /events [GET]
Traceback (most recent call last):
  File "/home/csommer/.local/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/csommer/.local/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/csommer/.local/lib/python3.5/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/flask/events.py", line 58, in get
    setattr(event, "display_text", event.template.format_str % tuple([arg.val for arg in event.args]))
TypeError: 'NoneType' object is not iterable

Event decode exception Value 255 out of range!
Traceback (most recent call last):
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/decoders/event_decoder.py", line 113, in decode_args
    arg_obj.deserialize(arg_data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/serializable_type.py", line 112, in deserialize
    memberVal.deserialize(data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 55, in deserialize
    self._deserialize('B', data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/type_base.py", line 58, in _deserialize
    self.val = struct.unpack_from(tformat, data, offset)[0]
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 42, in val
    self._check_val(val)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 34, in _check_val
    raise TypeRangeException(val)
fprime.common.models.serialize.type_exceptions.TypeRangeException: 255

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/client_socket/client_socket.py", line 137, in recv
    d.on_recv(chunk)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/distributor/distributor.py", line 208, in on_recv
    d.data_callback(msg)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/decoders/decoder.py", line 40, in data_callback
    decoded = self.decode_api(data)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/decoders/ch_decoder.py", line 76, in decode_api
    val_obj = self.decode_ch_val(data, ptr, ch_temp)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/common/decoders/ch_decoder.py", line 106, in decode_ch_val
    val_obj.deserialize(val_data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 55, in deserialize
    self._deserialize('B', data, offset)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/type_base.py", line 58, in _deserialize
    self.val = struct.unpack_from(tformat, data, offset)[0]
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 42, in val
    self._check_val(val)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime/common/models/serialize/i8_type.py", line 34, in _check_val
    raise TypeRangeException(val)
fprime.common.models.serialize.type_exceptions.TypeRangeException: 255

[2020-07-21 23:01:59,231] ERROR in app: Exception on /events [GET]
Traceback (most recent call last):
  File "/home/csommer/.local/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/csommer/.local/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/csommer/.local/lib/python3.5/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/csommer/.local/lib/python3.5/site-packages/fprime_gds/flask/events.py", line 58, in get
    setattr(event, "display_text", event.template.format_str % tuple([arg.val for arg in event.args]))
TypeError: 'NoneType' object is not iterable
```
 
### Suspected bug location:

In i8_type.py, the format characters are wrong, should be lowercase b instead of uppercase B:

    def serialize(self):
        """
        Utilize serialize decorator here...
        """
        return self._serialize('>b')

    def deserialize(self,data,offset):
        """
        Utilize deserialized decorator here...
        """
        self._deserialize('>b', data, offset)

    def getSize(self):
        return struct.calcsize('>b');

### Comment:

I16 and I32 don't seem affected by this bug.

**Comment by sommercharles** [comment]
Issue fixed through commit 3fbf687d44dba41fd8dd9af7cf1bbf6b80eb4831 in PR #190 
Thanks!
