### ISSUE TITLE
GDS shutdown `object has no attribute 'accept'`

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#1990]
| | |
|:---|:---|
|**_F´ Version_**| 3.2.0 |
|**_Affected Component_**|  GDS |
---
## Problem Description
Happened during a workshop, still need to reproduce.
At shutdown, the GDS errors out with
```
Exception in thread TcpCommThread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/joshuaa/p/fprime-gds/src/fprime_gds/common/communication/adapters/ip.py", line 111, in th_handler
    self.data_chunks.put(handler.read())
                         ^^^^^^^^^^^^^^
  File "/Users/joshuaa/p/fprime-gds/src/fprime_gds/common/communication/adapters/ip.py", line 308, in read
    return self.read_impl()
           ^^^^^^^^^^^^^^^^
  File "/Users/joshuaa/p/fprime-gds/src/fprime_gds/common/communication/adapters/ip.py", line 414, in read_impl
    self.open_impl()
  File "/Users/joshuaa/p/fprime-gds/src/fprime_gds/common/communication/adapters/ip.py", line 391, in open_impl
    (self.client, self.client_address) = self.socket.accept()
                                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'accept'
```

## How to Reproduce

Need to reproduce.

## Expected Behavior

Shutdown gracefully.

**Comment by matt392code** [comment]
Based on the traceback, this appears to be a race condition during shutdown where the TCP socket is being accessed after it's been set to None.

Breakdown of the issue:
1. The error occurs in the TCP communication thread (`TcpCommThread`)
2. The specific error path is:
   - `ip.py` line 111: Attempting to put data into queue from handler.read()
   - `ip.py` line 308: Calls read_impl()  
   - `ip.py` line 414: Calls open_impl()
   - `ip.py` line 391: Tries to call accept() on a socket that's None

This is likely happening because:
- During shutdown, the socket is being closed/set to None
- But the TCP communication thread is still trying to read from it
- There's no proper synchronization between the shutdown process and the communication thread

Here's a proposed fix approach:

```python
def shutdown(self):
    """
    Shutdown the TCP handler safely
    """
    with self._shutdown_lock:  # Add a threading lock
        if self.socket is not None:
            try:
                self.socket.close()
            finally:
                self.socket = None
                self._running = False  # Signal thread to stop

def read_impl(self):
    """
    Implementation of reading that checks socket validity
    """
    with self._shutdown_lock:
        if not self._running or self.socket is None:
            return None
        try:
            self.open_impl()
            # Rest of read implementation
```

The key points to address are:

1. Add proper thread synchronization around socket access
2. Add explicit shutdown state tracking
3. Handle the case where socket becomes None during operation
4. Ensure clean thread termination during shutdown
