### ISSUE TITLE
Cheetah version is using deprecated `cgi` package, removed in Python3.13

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#2973]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

See https://github.com/nasa/fprime/actions/runs/11395186564/job/31838364025

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/cheetah-compile", line 2, in <module>
    from Cheetah.CheetahWrapper import _cheetah_compile
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/Cheetah/CheetahWrapper.py", line 17, in <module>
    from Cheetah.Template import Template
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/Cheetah/Template.py", line 24, in <module>
    import cgi  # Used by .webInput() if the template is a CGI script.
    ^^^^^^^^^^
ModuleNotFoundError: No module named 'cgi'
```

Python3.13 release notes (ctrl+f `cgi`) https://docs.python.org/3/whatsnew/3.13.html

Fixed in Cheetah version: https://cheetahtemplate.org/news.html#id1

Need to upgrade our requirements.txt

**Comment by LeStarch** [comment]
This is a problem with an underlying dependency (`Cheetah3`/`CT3`).  There does not seem to be a fix for that dependency at this time.

Current work-around: revert to Python3.12 or below. 
Desired fix: remove XML code generate and Cheetah depenency

**Comment by LeStarch** [comment]
We fixed this with the legacy-cgi package.  Closing.
