### ISSUE TITLE
A stack-buffer-overflow error in Serializable.cpp line 55

### ISSUE THREAD

**Issue by zouyonghao** [nasa/fprime#429]
| | |
|:---|:---|
|**_F´ Version_**|1.5 |
|**_Affected Component_**| Fw  |
---
## Problem Description

A stack-buffer-overflow error in [Serializable.cpp line 55](https://github.com/nasa/fprime/blob/ada6e424b813e6434284bbde9f785656a61c8539/Fw/Types/Serializable.cpp#L55)

```
zyh@virtual:~/fprime$ ./build-fprime-automatic-native-ut/bin/Linux/Fw_Buffer_ut_exe 
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from Nominal
[ RUN      ] Nominal.BasicBuffer
[       OK ] Nominal.BasicBuffer (2 ms)
[ RUN      ] Nominal.Representations
=================================================================
==14450==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe10428264 at pc 0x0000004e1742 bp 0x7ffe10428020 sp 0x7ffe104277d0
READ of size 101 at 0x7ffe10428264 thread T0
    #0 0x4e1741 in __asan_memcpy (/home/zyh/fprime/build-fprime-automatic-native-ut/bin/Linux/Fw_Buffer_ut_exe+0x4e1741)
    #1 0x564c7e in Fw::SerializeBufferBase::copyFrom(Fw::SerializeBufferBase const&) /home/zyh/fprime/Fw/Types/Serializable.cpp:55:16
    #2 0x564e93 in Fw::SerializeBufferBase::operator=(Fw::SerializeBufferBase const&) /home/zyh/fprime/Fw/Types/Serializable.cpp:61:15
    #3 0x530b41 in test_representations() /home/zyh/fprime/Fw/Buffer/test/ut/TestBuffer.cpp:82:9
    #4 0x536cdf in Nominal_Representations_Test::TestBody() /home/zyh/fprime/Fw/Buffer/test/ut/TestBuffer.cpp:125:5
    #5 0x6750d0 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2433:10
    #6 0x63d3b9 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2469:14
    #7 0x5a6899 in testing::Test::Run() /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2508:5
    #8 0x5a8824 in testing::TestInfo::Run() /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2684:11
    #9 0x5a9654 in testing::TestSuite::Run() /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2816:28
    #10 0x5c826a in testing::internal::UnitTestImpl::RunAllTests() /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:5338:44
    #11 0x67cfc0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2433:10
    #12 0x643419 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:2469:14
    #13 0x5c7886 in testing::UnitTest::Run() /home/zyh/fprime/gtest/googletest-src/googletest/src/gtest.cc:4925:10
    #14 0x54349e in RUN_ALL_TESTS() /home/zyh/fprime/gtest/googletest-src/googletest/include/gtest/gtest.h:2473:46
    #15 0x53702f in main /home/zyh/fprime/Fw/Buffer/test/ut/TestBuffer.cpp:135:12
    #16 0x7f8a988bebf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #17 0x4229c9 in _start (/home/zyh/fprime/build-fprime-automatic-native-ut/bin/Linux/Fw_Buffer_ut_exe+0x4229c9)

Address 0x7ffe10428264 is located in stack of thread T0 at offset 132 in frame
    #0 0x52ee0f in test_representations() /home/zyh/fprime/Fw/Buffer/test/ut/TestBuffer.cpp:66

  This frame has 41 object(s):
    [32, 132) 'data' (line 67)
    [176, 232) 'buffer' (line 68) <== Memory access at offset 132 partially underflows this variable
    [272, 288) 'gtest_ar' (line 77)
    [304, 308) 'ref.tmp' (line 77)
    [320, 324) 'ref.tmp2' (line 77)
    [336, 344) 'ref.tmp4' (line 77)
    [368, 376) 'temp.lvalue'
    [400, 404) 'stat' (line 79)
    [416, 432) 'gtest_ar8' (line 80)
    [448, 452) 'ref.tmp9' (line 80)
    [464, 472) 'ref.tmp11' (line 80)
    [496, 504) 'temp.lvalue12'
    [528, 544) 'gtest_ar17' (line 84)
    [560, 564) 'ref.tmp18' (line 84)
    [576, 580) 'ref.tmp20' (line 84)
    [592, 600) 'ref.tmp22' (line 84)
    [624, 632) 'temp.lvalue23'
    [656, 660) 'out' (line 87)
    [672, 676) 'i30' (line 90)
    [688, 704) 'gtest_ar33' (line 91)
    [720, 724) 'ref.tmp34' (line 91)
    [736, 740) 'ref.tmp36' (line 91)
    [752, 760) 'ref.tmp38' (line 91)
    [784, 792) 'temp.lvalue39'
    [816, 832) 'gtest_ar42' (line 92)
    [848, 856) 'ref.tmp44' (line 92)
    [880, 888) 'temp.lvalue45'
    [912, 928) 'gtest_ar50' (line 94)
    [944, 948) 'ref.tmp51' (line 94)
    [960, 964) 'ref.tmp53' (line 94)
    [976, 984) 'ref.tmp55' (line 94)
    [1008, 1016) 'temp.lvalue56'
    [1040, 1056) 'gtest_ar63' (line 97)
    [1072, 1076) 'ref.tmp64' (line 97)
    [1088, 1092) 'ref.tmp66' (line 97)
    [1104, 1112) 'ref.tmp68' (line 97)
    [1136, 1144) 'temp.lvalue69'
    [1168, 1184) 'gtest_ar72' (line 98)
    [1200, 1204) 'ref.tmp73' (line 98)
    [1216, 1224) 'ref.tmp75' (line 98)
    [1248, 1256) 'temp.lvalue76'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/home/zyh/fprime/build-fprime-automatic-native-ut/bin/Linux/Fw_Buffer_ut_exe+0x4e1741) in __asan_memcpy
Shadow bytes around the buggy address:
  0x10004207cff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004207d000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004207d010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004207d020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004207d030: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x10004207d040: 00 00 00 00 00 00 00 00 00 00 00 00[04]f2 f2 f2
  0x10004207d050: f2 f2 00 00 00 00 00 00 00 f2 f2 f2 f2 f2 f8 f8
  0x10004207d060: f2 f2 f8 f2 f8 f2 f8 f2 f2 f2 00 f2 f2 f2 04 f2
  0x10004207d070: f8 f8 f2 f2 f8 f2 f8 f2 f2 f2 00 f2 f2 f2 f8 f8
  0x10004207d080: f2 f2 f8 f2 f8 f2 f8 f2 f2 f2 00 f2 f2 f2 f8 f2
  0x10004207d090: f8 f2 f8 f8 f2 f2 f8 f2 f8 f2 f8 f2 f2 f2 00 f2
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==14450==ABORTING
```

## How to Reproduce

1. Compile unit test with ASAN
2. Run build-fprime-automatic-native-ut/bin/Linux/Fw_Buffer_ut_exe
3. Program abort

## Expected Behavior

Run normally with ASAN.

**Comment by LeStarch** [comment]
Fixed by #443 I believe.
