### ISSUE TITLE
Ground GUI crashed after invalid commands 

### ISSUE THREAD

**Issue by pelmini** [nasa/fprime#84]
Submitted invalid command to ground station html gui, and the following crash happened: 
```
[2019-09-21 19:50:46,178] ERROR in app: Exception on /commands/cmdDisp.CMD_TEST_CMD_1 [PUT]
Traceback (most recent call last):
  File "/Users/fprime-venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fprime-venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fprime-venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/fprime-venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/fprime-venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/Documents/fprime/Gds/src/fprime_gds/flask/commands.py", line 97, in put
    self.sender.send_command(cmd_name_dict[command].opcode, arg_list)
  File "/Users/Documents/fprime/Gds/src/fprime_gds/common/pipeline/standard.py", line 217, in send_command```
    cmd_data = fprime_gds.common.data_types.cmd_data.CmdData(tuple(args), command_template)
  File "/Users/Documents/fprime/Gds/src/fprime_gds/common/data_types/cmd_data.py", line 72, in __init__
    self.convert_arg_value(val, typ)
  File "/Users/Documents/fprime/Gds/src/fprime_gds/common/data_types/cmd_data.py", line 171, in convert_arg_value
    arg_type.val = int(arg_val)
ValueError: invalid literal for int() with base 10: 'x'

**Comment by LeStarch** [comment]
I think this is fixed.  Need to verify.

**Comment by LeStarch** [comment]
Ground system does not crash, but just reports the error to HTML.

**Comment by LeStarch** [comment]
Full fix in-progress.

**Comment by LeStarch** [comment]
Fix should be delivered.
